DROP TABLE IF EXISTS #TABLA_DIAS
CREATE TABLE #TABLA_DIAS (ID INT, DIA VARCHAR(15))
INSERT INTO #TABLA_DIAS
SELECT 1 ID , 'SUNDAY' DIA UNION
SELECT 2 ID , 'MONDAY' DIA UNION
SELECT 3 ID , 'TUESDAY' DIA UNION
SELECT 4 ID , 'WEDNESDAY' DIA UNION
SELECT 5 ID , 'THURSDAY' DIA UNION
SELECT 6 ID , 'FRIDAY' DIA UNION
SELECT 7 ID , 'SATURDAY' DIA


SELECT * FROM #TABLA_DIAS

DROP TABLE IF EXISTS #TABLA_SEMANAS
CREATE TABLE #TABLA_SEMANAS
(
	ID INT
	,NOMBRE_PRIMER_DIA NVARCHAR(15)
	,NOMBRE_ULTIMO_DIA NVARCHAR(15)
	,FECHA_PRIMER_DIA DATE
	,FECHA_ULTIMO_DIA DATE
	,MES INT
)

DECLARE @NOMBRE_PRIMER_DIA_MES VARCHAR(15)= DATENAME(DW,(select  CAST(EOMONTH(getdate(),-1) AS datetime)+1 ))
DECLARE @NOMBRE_PRIMER_DIA_SEMANA VARCHAR(15)
DECLARE @PRIMER_DIA_MES INT=(SELECT ID FROM #TABLA_DIAS WHERE UPPER(DIA)=@NOMBRE_PRIMER_DIA_MES )

DECLARE @PRIMER_DIA_SEMANA DATE--=(select  CAST(EOMONTH(getdate(),-1) AS datetime)+1 )
DECLARE @ULTIMO_DIA_SEMANA DATE

SELECT 
@NOMBRE_PRIMER_DIA_MES DIA_INI_MES
--,@PRIMER_DIA_MES NUM_DIA_INI_MES
,@NOMBRE_PRIMER_DIA_MES NOMBRE_PRIMER_DIA_SEMANA
,@PRIMER_DIA_SEMANA  FECHA

