DECLARE  @TABLA_DIAS TABLE (ID INT, DIA VARCHAR(15))
INSERT INTO @TABLA_DIAS
	SELECT 1 ID , 'SUNDAY' DIA UNION
	SELECT 2 ID , 'MONDAY' DIA UNION
	SELECT 3 ID , 'TUESDAY' DIA UNION
	SELECT 4 ID , 'WEDNESDAY' DIA UNION
	SELECT 5 ID , 'THURSDAY' DIA UNION
	SELECT 6 ID , 'FRIDAY' DIA UNION
	SELECT 7 ID , 'SATURDAY' DIA UNION

	SELECT 1 ID , 'DOMINGO' DIA UNION
	SELECT 2 ID , 'LUNES' DIA UNION
	SELECT 3 ID , 'MARTES' DIA UNION
	SELECT 4 ID , 'MIÉRCOLES' DIA UNION
	SELECT 5 ID , 'JUEVES' DIA UNION
	SELECT 6 ID , 'VIERNES' DIA UNION
	SELECT 7 ID , 'SÁBADO' DIA

--SELECT * FROM #TABLA_DIAS


DECLARE  @TABLA_SEMANAS TABLE
(
	ID INT
	,NOMBRE_PRIMER_DIA NVARCHAR(15)
	,NOMBRE_ULTIMO_DIA NVARCHAR(15)
	,FECHA_PRIMER_DIA DATE
	,FECHA_ULTIMO_DIA DATE
	,MES INT
)
DECLARE @FECHA DATETIME=GETDATE()
DECLARE @NOMBRE_PRIMER_DIA_MES VARCHAR(15)= DATENAME(DW,(select  CAST(EOMONTH(@FECHA,-1) AS datetime)+1 ))
DECLARE @PRIMER_DIA_MES INT=(SELECT ID FROM @TABLA_DIAS WHERE UPPER(DIA)=@NOMBRE_PRIMER_DIA_MES )

DECLARE @FECHA_INI_SEMANA DATE=(select  CAST(EOMONTH(@FECHA,-1) AS datetime)+1 )
DECLARE @FECHA_FIN_SEMANA DATE=DATEADD(DAY,(7-@PRIMER_DIA_MES),@FECHA_INI_SEMANA)
DECLARE @CONT INT =1

WHILE(@FECHA_FIN_SEMANA<=EOMONTH(@FECHA))
BEGIN
	
		IF(@FECHA_FIN_SEMANA<EOMONTH(@FECHA))
		BEGIN
			INSERT INTO @TABLA_SEMANAS
			SELECT 
			@CONT
			,DATENAME(DW,@FECHA_INI_SEMANA) 
			,DATENAME(DW,@FECHA_FIN_SEMANA )
			,@FECHA_INI_SEMANA  
			,@FECHA_FIN_SEMANA  
			,MONTH(@FECHA)
		END
		-------------------------------------
		SET @FECHA_INI_SEMANA=DATEADD(DAY,1,@FECHA_FIN_SEMANA)
		SET @FECHA_FIN_SEMANA=DATEADD(DAY,6,@FECHA_INI_SEMANA)

		IF(@FECHA_FIN_SEMANA>=EOMONTH(@FECHA))
		BEGIN
			SET @FECHA_FIN_SEMANA=EOMONTH(@FECHA)
			INSERT INTO @TABLA_SEMANAS
			SELECT 
			@CONT+1
			,DATENAME(DW,@FECHA_INI_SEMANA) 
			,DATENAME(DW,@FECHA_FIN_SEMANA )
			,@FECHA_INI_SEMANA  
			,@FECHA_FIN_SEMANA
			,MONTH(@FECHA)

			BREAK
		END
		SET @CONT=@CONT+1
	
END
SELECT * FROM @TABLA_SEMANAS


--SELECT EOMONTH(GETDATE())