/********************************************************
OBTIENE LOS DATOS DEL TODOS LOS CLIENTES QUE HAN REALIZADO LLAMADAS
Y LOS REGISTRA EN LA TABLA LLAMADAS_TWILIO

ESTE PROCESO ES PARA SABER LA SUCURSAL, PAIS Y BLOQUE DE UNA LLAMADA
*/

DECLARE @ID VARCHAR(20)
DECLARE @NOMBRE NVARCHAR(100)
DECLARE CUR_M CURSOR
	FOR
		SELECT ClienteId,NombreCliente FROM LLAMADAS_TWILIO WHERE CAST(HoraInicioLlamada AS DATE)=CAST(GETDATE() AS DATE)
	OPEN CUR_M
	FETCH NEXT FROM CUR_M INTO  @ID,@NOMBRE
	WHILE @@FETCH_STATUS=0
		BEGIN
		DECLARE @ID_BLOQUE INT
		DECLARE @BLOQUE VARCHAR(5)
		DECLARE @BLOQUE_HIJO VARCHAR(5)
		DECLARE @ID_SUCU INT
		DECLARE @SUCURSAL NVARCHAR(80)
		DECLARE @URL NVARCHAR(100)
		DECLARE @ID_PAIS INT
		SELECT 
		--id_paciente
		@ID_BLOQUE= id_bloque
		,@BLOQUE=bloque
		,@BLOQUE_HIJO=bloque2
		,@ID_SUCU=id_sucursal
		,@SUCURSAL=sucursal
		,@ID_PAIS=id_pais
		,@URL=url_sistema FROM v_clientes WHERE paciente=@NOMBRE
		AND id_paciente=SUBSTRING(@ID,3,LEN(@ID)-4)

		UPDATE LLAMADAS_TWILIO 
		SET 
		IdBloque=@ID_BLOQUE
		,Bloque=@BLOQUE
		,IdSucursal=@ID_SUCU
		,Sucursal=@SUCURSAL
		,IdPais=@ID_PAIS
		,UrlSistema=@URL
		,BloqueHijo=@BLOQUE_HIJO
		WHERE ClienteId=@ID AND NombreCliente=@NOMBRE
		FETCH NEXT FROM CUR_M INTO @ID,@NOMBRE
	END
CLOSE CUR_M
DEALLOCATE CUR_M